CREATE TABLE [Role] (
	Id INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	Name VARCHAR(50) NOT NULL
)

CREATE TABLE [User] (
	Id INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	Roleid INT NOT NULL FOREIGN KEY REFERENCES [Role](Id),
	Username VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Gender VARCHAR(50) NOT NULL,
	Password VARCHAR(50) NOT NULL
)

CREATE TABLE [Header] (
	Id INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	CustomerID INT NOT NULL FOREIGN KEY REFERENCES [User](Id),
	StaffID INT NOT NULL FOREIGN KEY REFERENCES [User](Id),
	Date date NOT NULL
)

CREATE TABLE [Meat]	(
	Id INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	Name VARCHAR(50) NOT NULL
)

CREATE TABLE [Ramen] (
	Id INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	MeatId INT FOREIGN KEY REFERENCES [Meat](Id),
	Name VARCHAR(50) NOT NULL,
	Broth VARCHAR(50) NOT NULL,
	Price INT NOT NULL
)

CREATE TABLE [Detail] (
	HeaderId INT FOREIGN KEY REFERENCES [Header](Id),
	RamenId INT FOREIGN KEY REFERENCES [Ramen](Id),
	Quantity INT NOT NULL,
    Constraint DetailId PRIMARY KEY (HeaderId, RamenId)
)